name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*.*.*"  # Example: v0.1.0

permissions:
  id-token: write  # Required for trusted publishing
  contents: read

jobs:
  build-and-publish:
    name: Build and publish package to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi  # Optional if you used this in the PyPI form

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
